<?php

namespace Database\Seeders;

use App\Models\Language;
use App\Models\Translation;
use App\Services\Localization\LocalizationService;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class LocalizationSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            'language.view',
            'language.create',
            'language.update',
            'language.delete',
            'translation.view',
            'translation.update',
            'translation.import',
            'translation.export',
        ];

        foreach ($permissions as $permission) {
            Permission::findOrCreate($permission, 'web');
        }

        foreach (['super_admin', 'admin'] as $roleName) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->givePermissionTo($permissions);
        }

        $english = Language::query()->updateOrCreate(
            ['code' => 'en'],
            [
                'name' => 'English',
                'native_name' => 'English',
                'locale' => 'en',
                'flag' => 'backend/dist/img/lang/en.png',
                'is_default' => true,
                'is_active' => true,
                'direction' => 'ltr',
                'sort_order' => 10,
            ],
        );

        $khmer = Language::query()->updateOrCreate(
            ['code' => 'km'],
            [
                'name' => 'Khmer',
                'native_name' => 'ខ្មែរ',
                'locale' => 'km',
                'flag' => 'backend/dist/img/lang/kh.png',
                'is_default' => false,
                'is_active' => true,
                'direction' => 'ltr',
                'sort_order' => 20,
            ],
        );

        $french = Language::query()->updateOrCreate(
            ['code' => 'fr'],
            [
                'name' => 'French',
                'native_name' => 'Français',
                'locale' => 'fr',
                'flag' => 'backend/dist/img/lang/fr.png',
                'is_default' => false,
                'is_active' => true,
                'direction' => 'ltr',
                'sort_order' => 30,
            ],
        );

        $chinese = Language::query()->updateOrCreate(
            ['code' => 'zh'],
            [
                'name' => 'Chinese',
                'native_name' => '中文',
                'locale' => 'zh',
                'flag' => 'backend/dist/img/lang/cn.png',
                'is_default' => false,
                'is_active' => true,
                'direction' => 'ltr',
                'sort_order' => 40,
            ],
        );

        Language::query()->whereKeyNot($english->id)->update(['is_default' => false]);

        $translations = [
            'en' => [
                'frontend' => [
                    'brand' => 'Learning Management System',
                    'home' => 'Home',
                    'courses' => 'Courses',
                    'course_categories' => 'Course Categories',
                    'about' => 'About Us',
                    'about_system' => 'About LearnCore',
                    'welcome_speech' => 'Welcome Speech',
                    'general_info' => 'General Info (SPI)',
                    'vision_mission_goal' => 'Vision/Mission/Goal',
                    'services_recreation' => 'Services & Recreation',
                    'alumni' => 'Alumni',
                    'more' => 'More',
                    'instructors' => 'Instructors',
                    'contact' => 'Contact Us',
                    'faq' => 'FAQ',
                    'dashboard' => 'Dashboard',
                    'my_dashboard' => 'My Dashboard',
                    'teacher_dashboard' => 'Teacher Dashboard',
                    'admin_dashboard' => 'Admin Dashboard',
                    'my_courses' => 'My Courses',
                    'create_course' => 'Create Course',
                    'manage_lessons' => 'Manage Lessons',
                    'my_students' => 'My Students',
                    'assignments' => 'Assignments',
                    'quizzes' => 'Quizzes',
                    'grades' => 'Grades',
                    'student_grades' => 'Student Grades',
                    'learning_progress' => 'Learning Progress',
                    'certificates' => 'Certificates',
                    'reports' => 'Reports',
                    'calendar' => 'Calendar',
                    'notifications' => 'Notifications',
                    'profile' => 'Profile',
                    'edit_profile' => 'Edit Profile',
                    'settings' => 'Settings',
                    'logout' => 'Logout',
                    'login' => 'Login',
                    'register' => 'Register',
                    'guest_user' => 'Guest User',
                    'language' => 'Language',
                    'search_placeholder' => 'Search courses...',
                    'search' => 'Search',
                    'menu' => 'Menu',
                ],
                'admin' => [
                    'groups.users' => 'User Management',
                    'groups.academic' => 'Academic Management',
                    'groups.students' => 'Student Management',
                    'groups.teachers' => 'Teacher Management',
                    'groups.content' => 'Learning Content',
                    'groups.assessment' => 'Assessment',
                    'groups.communication' => 'Communication',
                    'groups.finance' => 'Finance',
                    'groups.reports' => 'Reports',
                    'groups.settings' => 'Settings',
                    'groups.api' => 'API',
                    'nav.dashboard' => 'Dashboard',
                    'nav.users' => 'Users',
                    'nav.roles' => 'Roles',
                    'nav.permissions' => 'Permissions',
                    'nav.faculties' => 'Faculties',
                    'nav.departments' => 'Departments',
                    'nav.academic_years' => 'Academic Years',
                    'nav.semesters' => 'Semesters',
                    'nav.students' => 'Students',
                    'nav.enrollments' => 'Enrollments',
                    'nav.attendance' => 'Attendance',
                    'nav.promotions' => 'Promotions',
                    'nav.teachers' => 'Teachers',
                    'nav.course_assignments' => 'Course Assignments',
                    'nav.class_schedules' => 'Class Schedules',
                    'nav.course_categories' => 'Course Categories',
                    'nav.courses' => 'Courses',
                    'nav.class_rooms' => 'Class Rooms',
                    'nav.modules' => 'Modules',
                    'nav.chapters' => 'Chapters',
                    'nav.lessons' => 'Lessons',
                    'nav.videos' => 'Videos',
                    'nav.documents' => 'Documents',
                    'nav.assignments' => 'Assignments',
                    'nav.resources' => 'Resources',
                    'nav.quizzes' => 'Quizzes',
                    'nav.question_banks' => 'Question Banks',
                    'nav.questions' => 'Questions',
                    'nav.exams' => 'Exams',
                    'nav.exam_schedule' => 'Exam Schedule',
                    'nav.exam_candidates' => 'Exam Candidates',
                    'nav.submissions' => 'Submissions',
                    'nav.assignment_submissions' => 'Assignment Submissions',
                    'nav.grading' => 'Grading',
                    'nav.results' => 'Results',
                    'nav.student_progress' => 'Student Progress',
                    'nav.certificates' => 'Certificates',
                    'nav.student_reports' => 'Student Reports',
                    'nav.attendance_reports' => 'Attendance Reports',
                    'nav.exam_reports' => 'Exam Reports',
                    'nav.finance_reports' => 'Finance Reports',
                    'nav.activity_logs' => 'Activity Logs',
                    'nav.languages' => 'Languages',
                    'nav.translations' => 'Translations',
                    'nav.my_courses' => 'My Courses',
                    'nav.available_courses' => 'Available Courses',
                    'nav.schedule' => 'Schedule',
                    'nav.quizzes_exams' => 'Quizzes / Exams',
                    'nav.grades' => 'Grades',
                    'nav.course_content' => 'Course Content',
                    'nav.gradebook' => 'Gradebook',
                    'nav.reports' => 'Reports',
                ],
            ],
            'km' => [
                'frontend' => [
                    'brand' => 'ប្រព័ន្ធគ្រប់គ្រងកម្មវិធីសិក្សា',
                    'home' => 'ទំព័រដើម',
                    'courses' => 'មុខវិជ្ជាសិក្សា',
                    'course_categories' => 'ប្រភេទមុខវិជ្ជា',
                    'about' => 'អំពីយើង',
                    'about_system' => 'អំពី LearnCore',
                    'welcome_speech' => 'សុន្ទរកថាស្វាគមន៍',
                    'general_info' => 'ព័ត៌មានទូទៅ (SPI)',
                    'vision_mission_goal' => 'ចក្ខុវិស័យ/បេសកកម្ម/គោលដៅ',
                    'services_recreation' => 'សេវាកម្ម និងការកម្សាន្ត',
                    'alumni' => 'អតីតនិស្សិត',
                    'more' => 'ច្រើនទៀត',
                    'instructors' => 'គ្រូបង្រៀន',
                    'contact' => 'ទំនាក់ទំនង',
                    'faq' => 'សំណួរញឹកញាប់',
                    'dashboard' => 'ផ្ទាំងគ្រប់គ្រង',
                    'my_dashboard' => 'ផ្ទាំងគ្រប់គ្រងរបស់ខ្ញុំ',
                    'teacher_dashboard' => 'ផ្ទាំងគ្រប់គ្រងគ្រូបង្រៀន',
                    'admin_dashboard' => 'ផ្ទាំងគ្រប់គ្រងអ្នកគ្រប់គ្រង',
                    'my_courses' => 'មុខវិជ្ជារបស់ខ្ញុំ',
                    'create_course' => 'បង្កើតមុខវិជ្ជា',
                    'manage_lessons' => 'គ្រប់គ្រងមេរៀន',
                    'my_students' => 'សិស្សរបស់ខ្ញុំ',
                    'assignments' => 'កិច្ចការ',
                    'quizzes' => 'ការប្រឡងខ្លី',
                    'grades' => 'ពិន្ទុ',
                    'student_grades' => 'ពិន្ទុសិស្ស',
                    'learning_progress' => 'វឌ្ឍនភាពសិក្សា',
                    'certificates' => 'វិញ្ញាបនបត្រ',
                    'reports' => 'របាយការណ៍',
                    'calendar' => 'ប្រតិទិន',
                    'notifications' => 'ការជូនដំណឹង',
                    'profile' => 'ប្រវត្តិរូប',
                    'edit_profile' => 'កែសម្រួលព័ត៌មាន',
                    'settings' => 'ការកំណត់',
                    'logout' => 'ចាកចេញ',
                    'login' => 'ចូលប្រើប្រាស់',
                    'register' => 'ចុះឈ្មោះ',
                    'guest_user' => 'អ្នកប្រើជាភ្ញៀវ',
                    'language' => 'ភាសា',
                    'search_placeholder' => 'ស្វែងរកមុខវិជ្ជា...',
                    'search' => 'ស្វែងរក',
                    'menu' => 'ម៉ឺនុយ',
                ],
                'admin' => [
                    'groups.users' => 'គ្រប់គ្រងអ្នកប្រើប្រាស់',
                    'groups.academic' => 'គ្រប់គ្រងការសិក្សា',
                    'groups.students' => 'គ្រប់គ្រងនិស្សិត',
                    'groups.teachers' => 'គ្រប់គ្រងគ្រូបង្រៀន',
                    'groups.content' => 'មាតិកាសិក្សា',
                    'groups.assessment' => 'ការវាយតម្លៃ',
                    'groups.communication' => 'ការទំនាក់ទំនង',
                    'groups.finance' => 'ហិរញ្ញវត្ថុ',
                    'groups.reports' => 'របាយការណ៍',
                    'groups.settings' => 'ការកំណត់',
                    'groups.api' => 'ចំណុចប្រទាក់កម្មវិធី',
                    'nav.dashboard' => 'ផ្ទាំងគ្រប់គ្រង',
                    'nav.users' => 'អ្នកប្រើប្រាស់',
                    'nav.roles' => 'តួនាទី',
                    'nav.permissions' => 'សិទ្ធិ',
                    'nav.faculties' => 'មហាវិទ្យាល័យ',
                    'nav.departments' => 'ដេប៉ាតឺម៉ង់',
                    'nav.academic_years' => 'ឆ្នាំសិក្សា',
                    'nav.semesters' => 'ឆមាស',
                    'nav.students' => 'និស្សិត',
                    'nav.enrollments' => 'ការចុះឈ្មោះ',
                    'nav.attendance' => 'វត្តមាន',
                    'nav.promotions' => 'ការឡើងថ្នាក់',
                    'nav.teachers' => 'គ្រូបង្រៀន',
                    'nav.course_assignments' => 'ចាត់តាំងវគ្គសិក្សា',
                    'nav.class_schedules' => 'កាលវិភាគសិក្សា',
                    'nav.course_categories' => 'ប្រភេទវគ្គសិក្សា',
                    'nav.courses' => 'វគ្គសិក្សា',
                    'nav.class_rooms' => 'ថ្នាក់រៀន',
                    'nav.modules' => 'ជំពូកមេរៀន',
                    'nav.chapters' => 'ជំពូក',
                    'nav.lessons' => 'មេរៀន',
                    'nav.videos' => 'វីដេអូ',
                    'nav.documents' => 'ឯកសារ',
                    'nav.assignments' => 'កិច្ចការ',
                    'nav.resources' => 'ធនធាន',
                    'nav.quizzes' => 'តេស្តខ្លី',
                    'nav.question_banks' => 'ធនាគារសំណួរ',
                    'nav.questions' => 'សំណួរ',
                    'nav.exams' => 'ការប្រឡង',
                    'nav.exam_schedule' => 'កាលវិភាគប្រឡង',
                    'nav.exam_candidates' => 'បេក្ខជនប្រឡង',
                    'nav.submissions' => 'ការដាក់ស្នើ',
                    'nav.assignment_submissions' => 'ការដាក់ស្នើកិច្ចការ',
                    'nav.grading' => 'ការដាក់ពិន្ទុ',
                    'nav.results' => 'លទ្ធផល',
                    'nav.student_progress' => 'វឌ្ឍនភាពនិស្សិត',
                    'nav.certificates' => 'វិញ្ញាបនបត្រ',
                    'nav.student_reports' => 'របាយការណ៍និស្សិត',
                    'nav.attendance_reports' => 'របាយការណ៍វត្តមាន',
                    'nav.exam_reports' => 'របាយការណ៍ប្រឡង',
                    'nav.finance_reports' => 'របាយការណ៍ហិរញ្ញវត្ថុ',
                    'nav.activity_logs' => 'កំណត់ត្រាសកម្មភាព',
                    'nav.languages' => 'ភាសា',
                    'nav.translations' => 'ការបកប្រែ',
                    'nav.my_courses' => 'វគ្គសិក្សារបស់ខ្ញុំ',
                    'nav.available_courses' => 'វគ្គសិក្សាដែលមាន',
                    'nav.schedule' => 'កាលវិភាគ',
                    'nav.quizzes_exams' => 'តេស្ត / ការប្រឡង',
                    'nav.grades' => 'ពិន្ទុ',
                    'nav.course_content' => 'មាតិកាវគ្គសិក្សា',
                    'nav.gradebook' => 'សៀវភៅពិន្ទុ',
                    'nav.reports' => 'របាយការណ៍',
                ],
            ],
            'fr' => [
                'frontend' => [
                    'brand' => 'Système de Gestion de l\'Apprentissage',
                    'home' => 'Accueil',
                    'courses' => 'Cours',
                    'course_categories' => 'Catégories de Cours',
                    'about' => 'À Propos',
                    'about_system' => 'À propos de LearnCore',
                    'welcome_speech' => 'Discours de bienvenue',
                    'general_info' => 'Infos générales (SPI)',
                    'vision_mission_goal' => 'Vision/Mission/Objectif',
                    'services_recreation' => 'Services et loisirs',
                    'alumni' => 'Alumni',
                    'more' => 'Plus',
                    'instructors' => 'Instructeurs',
                    'contact' => 'Contactez-nous',
                    'faq' => 'FAQ',
                    'dashboard' => 'Tableau de bord',
                    'my_dashboard' => 'Mon Tableau de bord',
                    'teacher_dashboard' => 'Tableau de bord Enseignant',
                    'admin_dashboard' => 'Tableau de bord Admin',
                    'my_courses' => 'Mes Cours',
                    'create_course' => 'Créer un Cours',
                    'manage_lessons' => 'Gérer les Leçons',
                    'my_students' => 'Mes Étudiants',
                    'assignments' => 'Devoirs',
                    'quizzes' => 'Quiz',
                    'grades' => 'Notes',
                    'student_grades' => 'Notes des Étudiants',
                    'learning_progress' => 'Progrès d\'Apprentissage',
                    'certificates' => 'Certificats',
                    'reports' => 'Rapports',
                    'calendar' => 'Calendrier',
                    'notifications' => 'Notifications',
                    'profile' => 'Profil',
                    'edit_profile' => 'Modifier le Profil',
                    'settings' => 'Paramètres',
                    'logout' => 'Se déconnecter',
                    'login' => 'Se connecter',
                    'register' => 'S\'inscrire',
                    'guest_user' => 'Utilisateur Invité',
                    'language' => 'Langue',
                    'search_placeholder' => 'Rechercher des cours...',
                    'search' => 'Rechercher',
                    'menu' => 'Menu',
                ],
                'admin' => [
                    'groups.users' => 'Gestion des Utilisateurs',
                    'groups.academic' => 'Gestion Académique',
                    'groups.students' => 'Gestion des Étudiants',
                    'groups.teachers' => 'Gestion des Enseignants',
                    'groups.content' => 'Contenu d\'Apprentissage',
                    'groups.assessment' => 'Évaluation',
                    'groups.communication' => 'Communication',
                    'groups.finance' => 'Finance',
                    'groups.reports' => 'Rapports',
                    'groups.settings' => 'Paramètres',
                    'groups.api' => 'API',
                    'nav.dashboard' => 'Tableau de bord',
                    'nav.users' => 'Utilisateurs',
                    'nav.roles' => 'Rôles',
                    'nav.permissions' => 'Autorisations',
                    'nav.faculties' => 'Facultés',
                    'nav.departments' => 'Départements',
                    'nav.academic_years' => 'Années Académiques',
                    'nav.semesters' => 'Semestres',
                    'nav.students' => 'Étudiants',
                    'nav.enrollments' => 'Inscriptions',
                    'nav.attendance' => 'Présence',
                    'nav.promotions' => 'Promotions',
                    'nav.teachers' => 'Enseignants',
                    'nav.course_assignments' => 'Attributions de Cours',
                    'nav.class_schedules' => 'Horaires de Classe',
                    'nav.course_categories' => 'Catégories de Cours',
                    'nav.courses' => 'Cours',
                    'nav.class_rooms' => 'Salles de Classe',
                    'nav.modules' => 'Modules',
                    'nav.chapters' => 'Chapitres',
                    'nav.lessons' => 'Leçons',
                    'nav.videos' => 'Vidéos',
                    'nav.documents' => 'Documents',
                    'nav.assignments' => 'Devoirs',
                    'nav.resources' => 'Ressources',
                    'nav.quizzes' => 'Quiz',
                    'nav.question_banks' => 'Banques de Questions',
                    'nav.questions' => 'Questions',
                    'nav.exams' => 'Examens',
                    'nav.exam_schedule' => 'Horaire des Examens',
                    'nav.exam_candidates' => 'Candidats aux Examens',
                    'nav.submissions' => 'Soumissions',
                    'nav.assignment_submissions' => 'Soumissions de Devoirs',
                    'nav.grading' => 'Notation',
                    'nav.results' => 'Résultats',
                    'nav.student_progress' => 'Progrès de l\'Étudiant',
                    'nav.certificates' => 'Certificats',
                    'nav.student_reports' => 'Rapports d\'Étudiants',
                    'nav.attendance_reports' => 'Rapports de Présence',
                    'nav.exam_reports' => 'Rapports d\'Examens',
                    'nav.finance_reports' => 'Rapports Financiers',
                    'nav.activity_logs' => 'Journaux d\'Activité',
                    'nav.languages' => 'Langues',
                    'nav.translations' => 'Traductions',
                    'nav.my_courses' => 'Mes Cours',
                    'nav.available_courses' => 'Cours Disponibles',
                    'nav.schedule' => 'Horaire',
                    'nav.quizzes_exams' => 'Quiz / Examens',
                    'nav.grades' => 'Notes',
                    'nav.course_content' => 'Contenu du Cours',
                    'nav.gradebook' => 'Carnet de Notes',
                    'nav.reports' => 'Rapports',
                ],
            ],
            'zh' => [
                'frontend' => [
                    'brand' => '学习管理系统',
                    'home' => '首页',
                    'courses' => '课程',
                    'course_categories' => '课程分类',
                    'about' => '关于我们',
                    'about_system' => '关于 LearnCore',
                    'welcome_speech' => '欢迎致辞',
                    'general_info' => '基本信息 (SPI)',
                    'vision_mission_goal' => '愿景/使命/目标',
                    'services_recreation' => '服务与娱乐',
                    'alumni' => '校友',
                    'more' => '更多',
                    'instructors' => '教师',
                    'contact' => '联系我们',
                    'faq' => '常见问题',
                    'dashboard' => '仪表板',
                    'my_dashboard' => '我的仪表板',
                    'teacher_dashboard' => '教师仪表板',
                    'admin_dashboard' => '管理员仪表板',
                    'my_courses' => '我的课程',
                    'create_course' => '创建课程',
                    'manage_lessons' => '管理课时',
                    'my_students' => '我的学生',
                    'assignments' => '作业',
                    'quizzes' => '测验',
                    'grades' => '成绩',
                    'student_grades' => '学生成绩',
                    'learning_progress' => '学习进度',
                    'certificates' => '证书',
                    'reports' => '报告',
                    'calendar' => '日历',
                    'notifications' => '通知',
                    'profile' => '个人资料',
                    'edit_profile' => '编辑资料',
                    'settings' => '设置',
                    'logout' => '退出登录',
                    'login' => '登录',
                    'register' => '注册',
                    'guest_user' => '访客',
                    'language' => '语言',
                    'search_placeholder' => '搜索课程...',
                    'search' => '搜索',
                    'menu' => '菜单',
                ],
                'admin' => [
                    'groups.users' => '用户管理',
                    'groups.academic' => '教务管理',
                    'groups.students' => '学生管理',
                    'groups.teachers' => '教师管理',
                    'groups.content' => '教学内容',
                    'groups.assessment' => '考核评估',
                    'groups.communication' => '互动沟通',
                    'groups.finance' => '财务管理',
                    'groups.reports' => '报表统计',
                    'groups.settings' => '系统设置',
                    'groups.api' => '接口管理',
                    'nav.dashboard' => '仪表板',
                    'nav.users' => '用户列表',
                    'nav.roles' => '角色管理',
                    'nav.permissions' => '权限设置',
                    'nav.faculties' => '院系管理',
                    'nav.departments' => '专业管理',
                    'nav.academic_years' => '学年设置',
                    'nav.semesters' => '学期设置',
                    'nav.students' => '学生信息',
                    'nav.enrollments' => '入学注册',
                    'nav.attendance' => '考勤管理',
                    'nav.promotions' => '分班晋升',
                    'nav.teachers' => '教师信息',
                    'nav.course_assignments' => '任课分配',
                    'nav.class_schedules' => '课表安排',
                    'nav.course_categories' => '课程分类',
                    'nav.courses' => '课程管理',
                    'nav.class_rooms' => '教室管理',
                    'nav.modules' => '模块',
                    'nav.chapters' => '课程章节',
                    'nav.lessons' => '课时列表',
                    'nav.videos' => '视频资源',
                    'nav.documents' => '文档资料',
                    'nav.assignments' => '作业管理',
                    'nav.resources' => '辅助资源',
                    'nav.quizzes' => '在线测验',
                    'nav.question_banks' => '题库管理',
                    'nav.questions' => '试题列表',
                    'nav.exams' => '考试管理',
                    'nav.exam_schedule' => '考试日程',
                    'nav.exam_candidates' => '参考名单',
                    'nav.submissions' => '答卷提交',
                    'nav.assignment_submissions' => '作业提交',
                    'nav.grading' => '教师阅卷',
                    'nav.results' => '成绩列表',
                    'nav.student_progress' => '学习进度',
                    'nav.certificates' => '证书管理',
                    'nav.student_reports' => '学生报表',
                    'nav.attendance_reports' => '考勤报表',
                    'nav.exam_reports' => '成绩分析',
                    'nav.finance_reports' => '财务报表',
                    'nav.activity_logs' => '操作日志',
                    'nav.languages' => '多语言设置',
                    'nav.translations' => '语言包翻译',
                    'nav.my_courses' => '我的课程',
                    'nav.available_courses' => '可选课程',
                    'nav.schedule' => '日程课表',
                    'nav.quizzes_exams' => '测验考试',
                    'nav.grades' => '我的成绩',
                    'nav.course_content' => '课程内容',
                    'nav.gradebook' => '记分册',
                    'nav.reports' => '报表中心',
                ],
            ],
        ];

        foreach ([$english, $khmer, $french, $chinese] as $language) {
            foreach ($translations[$language->code] as $group => $items) {
                foreach ($items as $key => $value) {
                    Translation::query()->updateOrCreate(
                        ['language_id' => $language->id, 'group' => $group, 'key' => $key],
                        ['value' => $value],
                    );
                }
            }
        }

        app(LocalizationService::class)->clearCache();
    }
}
